version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="spotify-clone"
    ports: 
    - "27017:27017"  
  
  #failed to run docker compose up with error In file './docker-compose.yml', services 'image' must be a mapping not a string